### ISSUE TITLE
Symlink already exists

### ISSUE THREAD

**Issue by jameshloving** [bitnami/bitnami-docker-tomcat#62]
When trying to build a container via `docker-compose up`, I get the following error:

> admin_1      | Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami> /tomcat/data' -> '/opt/bitnami/tomcat/webapps'
> vagrant_admin_1 exited with code 1

My Dockerfile:
```
FROM bitnami/tomcat:latest
COPY *war /app
```

Relevant portion of my docker-compose.yml:
```
  admin:
    build:
      context: .config/dockerfiles
      dockerfile: admin.dockerfile
    networks:
      admin_net:
        ipv4_address: 10.1.1.2
    ports:
      - 8080:8080
      - 8443:8443
```

I have an Ansible playbook that is orchestrating this entire process, including copying the appropriate WAR file to the `.config/dockerfiles/` directory prior to executing `docker-compose up`.
