### ISSUE TITLE
Question: Where to set JAVA and CATALINA OPTS

### ISSUE THREAD

**Issue by StefanSchubert** [bitnami/bitnami-docker-tomcat#80]
Hi,

if have tried to configure the JAVA_OPTS via setenv.sh in 
/opt/bitnami/tomecat/bin

but it seems that this changes are overwritten (i.e. destroyed through appending by the bootstrapping). 

also /bitnami/tomcat/bin  and .nami/registry.json doesn't seem to work.

What it the correct place if I need to change the settings? I need to provide the tomcat with more heap space and to enable the JMX ports, so that I can fetch the vital jvm params for monitoring.

Thanks in advance
Stefan

**Comment by gongomgra** [comment]
Hi,

You can set the JAVA_OPTS environment variable when running the container or set it in the docker-compose.yml file. The values you set in that environment variable won’t be concatenated with the default values, so you will need to explicitly include the default parameters as shown below

```
docker run -e JAVA_OPTS="-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8 [YOUR_CUSTOM_OPTIONS]" --name tomcat bitnami/tomcat:9.0
```

Another option is to modify the `libtomcat.sh` script present into the `rootfs` folder of the Tomcat version and OS of your choice, and customise the JAVA_OPTS environment variable in that file. After that, you will have to build your custom Tomcat docker image with your changes.

Hope it helps,
Gonzalo

**Comment by gongomgra** [comment]
Hi,

How did you define the environment variable in the `docker-compose.yml` file? I made it work both with a `docker run` and `docker-compose`. For `docker run` I exactly run the next command. Note I’m manually exposing the port 9000 from the container to my computer

```
docker run -e CATALINA_OPTS="-Xms256m -Xmx512m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false" --rm -it -p 9000:9000 -p 8080:8080 bitnami/tomcat:9.0
```

After that, I connected to `localhost:9000` on jconsole and I can see the monitoring data.

For `docker-compose` I modified the file to look as below, and running `docker-compose up` allowed me to connect with jconsole to `localhost:9000` without issues

```
version: '2'

services:
  tomcat:
    image: 'bitnami/tomcat:9.0'
    ports:
      - '8080:8080'
      - '9000:9000'
    volumes:
      - 'tomcat_data:/bitnami'
    environment:
      - 'CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false'
      - 'JAVA_OPTS=-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8 -Xms256m -Xmx512m'

volumes:
  tomcat_data:
    driver: local
```

Can you try using the `docker-compose.yml` file above? Find below a screenshot of jconsole connected to port 9000

![Screen Shot 2019-11-06 at 16 52 51](https://user-images.githubusercontent.com/6660452/68314111-f522ca80-00b5-11ea-93c6-30fa6aed2a57.png)

Regards,
Gonzalo
